name: Release Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  release:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Extract git commit digest
        id: version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}:${{ env.VERSION }} .
          docker tag ghcr.io/${{ env.REPO_NAME }}:${{ env.VERSION }} ghcr.io/${{ env.REPO_NAME }}:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.VERSION }}
          docker push ghcr.io/${{ env.REPO_NAME }}:latest
